### ISSUE TITLE
Can't stop the note from playing.

### ISSUE THREAD

**Issue by oldtimerza** [goatonabicycle/note-generation#1]
When I start the application and then click the "Play" button , it starts to play the first note that is highlighted in blue.

The "Play" button changes to a "Stop" button. But clicking it has no effect. The note continues to play on repeat.

I get the following error message in the console logs:
Uncaught Error: Invalid argument(s) to setValueAtTime: "undefined2", 0

Using Firefox 80.0(64-bit)

**Comment by goatonabicycle** [comment]
Interesting! 
That's definitely not supposed to happen. 
Thank you so much, I really appreciate it.

**Comment by oldtimerza** [comment]
Fixes #3
